spring.application.name=pop

# PostgreSQL Aiven Configuration - Banco db_pop
spring.datasource.url=jdbc:postgresql://pg-33b9ede7-daviarakaki2009-9857.k.aivencloud.com:11541/db_pop?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.org.hibernate.SQL=DEBUG
