spring.application.name=pop

# ==========================================
# POSTGRESQL - Aiven
# ==========================================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# JPA — deixa o Flyway criar as tabelas
# ==========================================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==========================================
# FLYWAY
# ==========================================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migrations
spring.flyway.baseline-on-migrate=true

# ==========================================
# JWT
# ==========================================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# ==========================================
# Logging
# ==========================================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.flywaydb=INFO