spring.application.name=pop
# ==========================================
# H2 DATABASE (LOCAL - PARA TESTES)
# ==========================================
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
# ==========================================
# POSTGRESQL (COMENTADO POR ENQUANTO)
# ==========================================
# spring.datasource.url=jdbc:postgresql://pg-33b9ede7-daviarakaki2009-9857.k.aivencloud.com:11541/db_pop?sslmode=require
# spring.datasource.username=avnadmin
# spring.datasource.password=${DB_PASSWORD}
# spring.datasource.driver-class-name=org.postgresql.Driver
# ==========================================
# JPA Configuration
# ==========================================
spring.jpa.show-sql=true
# ==========================================
# Logging
# ==========================================
logging.level.org.hibernate.SQL=DEBUG
# ==========================================
# JWT Configuration
# ==========================================
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}